name: chocolatine

on:
  push:
    branches-ignore:
     - 'ga-ignore-**'
  pull_request:
    branches-ignore:
     - 'ga-ignore-**'


env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-SVR-500-NAN-5-1-survivornext-lucas.hauszler.git"

jobs:
  trombi-eslint:
    name: Check coding style using eslint in "./trombi" folder
    runs-on: ubuntu-latest
    env:
      trombi: trombi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          cd ${{ env.trombi }}
          npm install

      - name: Run eslint
        run: |
          cd ${{ env.trombi }}
          npm run lint

  push_to_mirror:
    name: Pushes the current repository files to a given mirror repository
    needs: [trombi-eslint, trombi-tests]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
